name: FireZeus
version: 1.0.0
author: Adam Morris
description: Adds flame particles to a players head
main: com.github.aimorris.minecraft_fire_zeus.FireZeus
api-version: 1.15
commands:
  firezeus:
    description: Adds flaming particles to your head!
    usage: /<command>
permissions:
  flaminghead.flaminghead:
    description: Gives access to the /firezeus command.
    default: op